const SCRIPT_URL="https://script.google.com/macros/s/AKfycbwct7tEZPpWxZNRYElhCPGQkL7IXXN96PswSLwlwFwo5DZuD7mH5t3kHaTOq69Z86cn-g/exec";
const session=JSON.parse(sessionStorage.getItem("sitaraUser")||"{}");
const sessionToken=String(session.session_token||"").trim();
const $=id=>document.getElementById(id);
function esc(v){return String(v??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]));}
function dateID(v){if(!v)return "-";const d=new Date(v);return isNaN(d)?esc(v):d.toLocaleDateString("id-ID",{weekday:"long",day:"2-digit",month:"long",year:"numeric"});}
function initials(name){return String(name||"Ketua BEM").trim().split(/\s+/).filter(Boolean).slice(0,2).map(x=>x[0]).join("").toUpperCase()||"KB";}
async function api(action,data={}){const r=await fetch(SCRIPT_URL,{method:"POST",headers:{"Content-Type":"text/plain;charset=utf-8"},body:JSON.stringify({action,session_token:sessionToken,...data})});return r.json();}
function setProfile(){const name=session.nama_lengkap||session.nama||session.name||"Ketua BEM";const i=initials(name);["profileAvatar","topbarAvatar"].forEach(x=>$(x)&&($(x).textContent=i));if($("profileName"))$("profileName").textContent=name;if($("welcomeTitle"))$("welcomeTitle").textContent=name;const role=session.role||"Pimpinan";if($("profileRole"))$("profileRole").textContent=role;}
async function load(){setProfile();$("currentDate").textContent=dateID(new Date());try{const r=await api("getDashboardKetuaBEM");if(!r.success)throw Error(r.message||"Gagal memuat dashboard.");const d=r.data||{};$("statMenunggu").textContent=d.stats?.menunggu??0;$("statRevisi").textContent=d.stats?.revisi??0;$("statDisetujui").textContent=d.stats?.disetujui??0;$("statDitolak").textContent=d.stats?.ditolak??0;renderItems(d.pengajuan||[]);renderActivities(d.aktivitas||[]);}catch(e){$("recentList").innerHTML=`<div class="empty-state">${esc(e.message)}</div>`;$("activityList").innerHTML=`<div class="empty-state">Belum ada aktivitas.</div>`;}}
function renderItems(a){const body=$("recentList");if(!a.length){body.innerHTML='<tr><td colspan="6" class="empty-state">Tidak ada pengajuan yang menunggu persetujuan.</td></tr>';return;}body.innerHTML=a.slice(0,8).map(x=>`<tr><td><strong>${esc(x.judul)}</strong><small>${esc(x.pengajuan_id)}</small></td><td>${esc(x.jenis)}</td><td>${esc(x.asal_kementerian)}</td><td>${dateID(x.tanggal_pengajuan)}</td><td><span class="status-badge status-warning">${esc(x.status)}</span></td><td><a class="quick-open" href="pengajuan/detail/index.html?id=${encodeURIComponent(x.pengajuan_id)}">Buka</a></td></tr>`).join("");}
function renderActivities(a){const box=$("activityList");if(!a.length){box.innerHTML='<div class="empty-state">Belum ada aktivitas.</div>';return;}box.innerHTML=a.slice(0,8).map(x=>`<div class="activity-item"><div class="activity-dot"></div><div><strong>${esc(x.aksi)}</strong><p>${esc(x.judul||x.pengajuan_id)}</p></div><time>${dateID(x.waktu)}</time></div>`).join("");}
$("logoutButton")?.addEventListener("click",()=>{sessionStorage.removeItem("sitaraUser");location.href="../../login/index.html";});
load();