const API_URL='https://script.google.com/macros/s/AKfycbwct7tEZPpWxZNRYElhCPGQkL7IXXN96PswSLwlwFwo5DZuD7mH5t3kHaTOq69Z86cn-g/exec';
const raw=sessionStorage.getItem('sitaraUser');
if(!raw) location.href='../../../login/index.html';
let user; try{user=JSON.parse(raw)}catch(e){sessionStorage.removeItem('sitaraUser');location.href='../../../login/index.html'}
if(user&&(String(user.role||'').toLowerCase()!=='mensetkab'||(user.kementerian_id&&user.kementerian_id!=='KEM001'))){alert('Akses ditolak.');location.href='../../../login/index.html'}
let rows=[],filter="all";
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const badge=s=>{const x=String(s||'').toLowerCase();let c='status-info';if(x.includes('selesai')||x.includes('disetujui'))c='status-success';else if(x.includes('revisi')||x.includes('menunggu'))c='status-warning';else if(x.includes('tolak'))c='status-danger';return `<span class="status-badge ${c}">${esc(s||'-')}</span>`};
const typeClass=s=>{s=String(s||'').toLowerCase();if(s.includes('proposal'))return'type-proposal';if(s.includes('lpj'))return'type-lpj';if(s.includes('surat'))return'type-surat';if(s.includes('rab')||s.includes('anggaran'))return'type-rab';if(s.includes('form'))return'type-form';return'type-other'};
const date=v=>{const d=new Date(v);return v&&!isNaN(d)?d.toLocaleDateString('id-ID',{day:'2-digit',month:'short',year:'numeric'}):'-'};
async function post(a,x={}){return(await fetch(API_URL,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify({action:a,session_token:user.session_token,...x})})).json()}
function render(){const q=(document.getElementById('search').value||'').toLowerCase();const data=rows.filter(x=>{const t=(x.judul+' '+x.nomor_pengajuan+' '+x.asal_kementerian).toLowerCase();const f=filter==='all'||(filter==='proposal'&&String(x.jenis).toLowerCase().includes('proposal'))||(filter==='lpj'&&String(x.jenis).toLowerCase().includes('lpj'));return(!q||t.includes(q))&&f});document.getElementById('count').textContent=`${data.length} pengajuan`;document.getElementById('body').innerHTML=data.length?data.map(x=>`<tr><td><strong>${esc(x.nomor_pengajuan)}</strong><small>${esc(x.judul||'-')}</small></td><td>${esc(x.asal_kementerian)}</td><td>${esc(x.judul||'-')}</td><td><span class="type-badge ${typeClass(x.jenis)}">${esc(x.jenis||'-')}</span></td><td>${badge(x.status_label)}</td><td>${date(x.tanggal_pengajuan)}</td><td><a class="btn-open" href="detail/index.html?id=${encodeURIComponent(x.pengajuan_id)}">Buka</a></td></tr>`).join(''):`<tr><td colspan="7" class="empty-state">Tidak ada pengajuan.</td></tr>`}
async function init(){const name=user.nama_lengkap||user.nama||'Mensetkab';const av=(name.trim().split(/\s+/).filter(Boolean).slice(0,2).map(x=>x[0]).join('')||'MS').toUpperCase();document.getElementById('profileName').textContent=name;document.getElementById('profileAvatar').textContent=av;document.getElementById('topbarAvatar').textContent=av;document.getElementById('currentDate').textContent=new Date().toLocaleDateString('id-ID',{weekday:'long',day:'numeric',month:'long',year:'numeric'});try{const r=await post('getPengajuanMasukMensetkab');if(!r.success)throw Error(r.message);rows=r.data||[];render()}catch(e){document.getElementById('body').innerHTML=`<tr><td colspan="7" class="empty-state">${esc(e.message)}</td></tr>`}}
document.getElementById('search').oninput=render;document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');filter=b.dataset.filter;render()});document.getElementById('logoutBtn').onclick=()=>{if(confirm('Apakah Anda yakin ingin keluar dari SITARA?')){sessionStorage.removeItem('sitaraUser');location.href='../../../login/index.html'}};init();