const API_URL="https://script.google.com/macros/s/AKfycbwct7tEZPpWxZNRYElhCPGQkL7IXXN96PswSLwlwFwo5DZuD7mH5t3kHaTOq69Z86cn-g/exec";
const sessionData=sessionStorage.getItem("sitaraUser");
let user=null,rows=[];
try{user=JSON.parse(sessionData||"null");}catch(e){}
if(!user||user.role!=="kementerian"||user.kementerian_id!=="KEM001"){window.location.href="/login/index.html";}else{initialize();}
function initialize(){const name=user.nama_lengkap||user.nama||"Kementerian Sekretariat Kabinet",initial="KS";document.getElementById("profileName").textContent=name;document.getElementById("profileAvatar").textContent=initial;document.getElementById("topbarAvatar").textContent=initial;document.getElementById("currentDate").textContent=new Date().toLocaleDateString("id-ID",{weekday:"long",day:"numeric",month:"long",year:"numeric"});document.getElementById("logoutButton").addEventListener("click",()=>{if(!confirm("Apakah Anda yakin ingin keluar dari SITARA?"))return;sessionStorage.removeItem("sitaraUser");window.location.href="/login/index.html";});document.getElementById("historySearch").addEventListener("input",render);document.getElementById("historyStatus").addEventListener("change",render);load();}
async function load(){const box=document.getElementById("historyList");try{const response=await fetch(API_URL,{method:"POST",body:JSON.stringify({action:"getRiwayatPengajuan",session_token:user.session_token})});const result=await response.json();if(!result.success)throw new Error(result.message||"Gagal memuat riwayat.");rows=Array.isArray(result.data)?result.data:[];const statuses=[...new Set(rows.map(x=>getStatusInfo(x.status_riwayat).label).filter(Boolean))];document.getElementById("historyStatus").innerHTML='<option value="">Semua Status</option>'+statuses.map(s=>`<option value="${escapeHtml(s)}">${escapeHtml(s)}</option>`).join("");render();}catch(error){box.innerHTML=`<div class="history-error"><strong>Gagal memuat riwayat</strong><br>${escapeHtml(error.message)}</div>`;}}
function render(){const q=document.getElementById("historySearch").value.trim().toLowerCase(),st=document.getElementById("historyStatus").value;const filtered=rows.filter(x=>{const text=(x.pengajuan_id+" "+x.perihal+" "+x.asal_kementerian).toLowerCase(),label=getStatusInfo(x.status_riwayat).label;return(!q||text.includes(q))&&(!st||label===st);});const box=document.getElementById("historyList");if(!filtered.length){box.innerHTML='<div class="history-empty">Tidak ada riwayat yang sesuai.</div>';return;}box.innerHTML=filtered.map(x=>{const status=getStatusInfo(x.status_riwayat);return`<article class="history-card"><div class="history-card-head"><div><div class="history-number">${escapeHtml(x.pengajuan_id)}</div><div class="history-title">${escapeHtml(x.perihal||"Tanpa judul")}</div><div class="history-meta">${escapeHtml(getJenisLabel(x.jenis))} · ${escapeHtml(x.asal_kementerian||"-")}</div></div><span class="history-status status-${status.cls}">${escapeHtml(status.label)}</span></div><div class="history-flow"><span class="history-unit">${escapeHtml(formatUnit(x.dari_unit))}</span><span class="history-arrow">→</span><span class="history-unit">${escapeHtml(formatUnit(x.ke_unit))}</span></div><div class="history-action">${escapeHtml(x.aksi||"Perubahan status")}</div>${x.catatan?`<div class="history-note">${escapeHtml(x.catatan)}</div>`:""}<div class="history-time">${formatDateTime(x.waktu)}</div></article>`;}).join("");}
function normalizeStatus(v){return String(v||"").trim().toLowerCase().replace(/_/g," ").replace(/\s+/g," ");}
function getStatusInfo(value){const raw=String(value||"").trim(),n=normalizeStatus(raw);const map=[[/^diajukan$/, ["Diajukan","diajukan"]],[/menunggu verifikasi|perlu verifikasi/, ["Menunggu Verifikasi","menunggu-verifikasi"]],[/perlu revisi|^revisi$/, ["Perlu Revisi","perlu-revisi"]],[/menunggu persetujuan mensetkab|menunggu persetujuan menteri sekretariat kabinet/, ["Menunggu Persetujuan Mensetkab","menunggu-mensetkab"]],[/menunggu persetujuan ketua bem|menunggu persetujuan ketua/, ["Menunggu Persetujuan Ketua BEM","menunggu-ketua"]],[/diajukan ke dpm/, ["Diajukan ke DPM","diajukan-dpm"]],[/disetujui dpm/, ["Disetujui DPM","disetujui-dpm"]],[/diajukan ke fakultas/, ["Diajukan ke Fakultas","diajukan-fakultas"]],[/disetujui fakultas/, ["Disetujui Fakultas","disetujui-fakultas"]],[/menunggu dokumen fakultas/, ["Menunggu Dokumen Fakultas","menunggu-fakultas"]],[/dalam proses|diproses|proses/, ["Dalam Proses","dalam-proses"]],[/selesai/, ["Selesai","selesai"]],[/ditolak/, ["Ditolak","ditolak"]]];for(const[rx,info]of map)if(rx.test(n))return{label:info[0],cls:info[1]};return{label:raw||"-",cls:"lainnya"};}
function formatUnit(value){const raw=String(value||"").trim(),n=raw.toLowerCase();if(raw==="KEM001"||n==="biro agata"||n==="kemensetkab")return"Kementerian Sekretariat Kabinet";if(n==="mensetkab"||n==="menteri sekretariat kabinet")return"Menteri Sekretariat Kabinet";if(n==="ketua"||n==="ketua bem")return"Ketua BEM";if(n==="kemenkeu"||n==="kementerian keuangan")return"Kementerian Keuangan";return raw;}
function getJenisLabel(v){const n=String(v||"").trim().toLowerCase();return n==="proposal"?"Proposal":n==="lpj"?"LPJ":String(v||"-");}
function formatDateTime(v){if(!v)return"-";const d=new Date(v);return isNaN(d)?"-":d.toLocaleString("id-ID",{day:"numeric",month:"long",year:"numeric",hour:"2-digit",minute:"2-digit"});}
function escapeHtml(v){return String(v??"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&#039;");}
