const API_URL="https://script.google.com/macros/s/AKfycbwct7tEZPpWxZNRYElhCPGQkL7IXXN96PswSLwlwFwo5DZuD7mH5t3kHaTOq69Z86cn-g/exec",LOGIN_URL="/login/index.html";
let user=null;try{user=JSON.parse(sessionStorage.getItem("sitaraUser")||"null")}catch(e){}
if(!user||String(user.role||"").toLowerCase()!=="kementerian"||String(user.kementerian_id||"").toUpperCase()!=="KEM002"){sessionStorage.removeItem("sitaraUser");location.href=LOGIN_URL;}else{init();}
function init(){const name=user.nama_unit||user.nama_lengkap||"Kementerian Keuangan",i=ini(name);for(const id of ["profileName"])document.getElementById(id).textContent=name;for(const id of ["profileAvatar","topbarAvatar"])document.getElementById(id).textContent=i;document.getElementById("profileRole").textContent="Kementerian";document.getElementById("currentDate").textContent=new Date().toLocaleDateString("id-ID",{weekday:"long",day:"numeric",month:"long",year:"numeric"});document.getElementById("logoutButton").onclick=logout;load();}
function ini(n){const p=String(n).trim().split(/\s+/).filter(Boolean);return p.length<2?p[0].slice(0,2).toUpperCase():p.slice(0,2).map(x=>x[0]).join("").toUpperCase();}
function logout(){if(confirm("Apakah kamu yakin ingin keluar dari SITARA?")){sessionStorage.removeItem("sitaraUser");location.href=LOGIN_URL;}}
async function load(){const id=new URLSearchParams(location.search).get("id"),box=document.getElementById("detailContainer");if(!id){box.innerHTML='<div class="detail-error">ID pengajuan tidak ditemukan.</div>';return;}try{const r=await fetch(API_URL,{method:"POST",headers:{"Content-Type":"text/plain;charset=utf-8"},body:JSON.stringify({action:"getDetailPengajuanKemenkeu",session_token:user.session_token,pengajuan_id:id})});const x=await r.json();if(!x.success)throw new Error(x.message||"Gagal memuat detail.");render(x.data||{});}catch(e){box.innerHTML=`<div class="detail-error"><strong>Gagal memuat detail</strong><br>${esc(e.message)}</div>`;}}
function render(d){const p=d.pengajuan||{},docs=Array.isArray(d.dokumen)?d.dokumen:[];const sp=docs.filter(x=>norm(x.jenis_dokumen).includes("surat pencairan dana")||norm(x.nama_file).includes("surat pencairan dana"));document.getElementById("detailContainer").innerHTML=`<div class="detail-card"><div class="detail-status"><span>Diterima Kementerian Keuangan</span></div><h1>${esc(p.pengajuan_id||"-")}</h1><p class="lead">${esc(p.judul_pengajuan||p.perihal||"Pengajuan")}</p><div class="grid"><div><span>Jenis Pengajuan</span><strong>${esc(p.jenis_pengajuan||"-")}</strong></div><div><span>Asal Kementerian</span><strong>${esc(d.asal_kementerian||p.asal_kementerian||"-")}</strong></div><div><span>Tanggal Pengajuan</span><strong>${date(p.tanggal_pengajuan)}</strong></div><div><span>Status</span><strong>Dokumen diterima</strong></div></div><section class="docs"><h2>Surat Pencairan Dana</h2>${sp.length?sp.slice(-1).map(doc).join(""):'<div class="empty">Surat Pencairan Dana tidak ditemukan.</div>'}</section><div class="note">Dokumen ini diteruskan secara internal melalui SITARA oleh Kementerian Sekretariat Kabinet.</div></div>`;}
function doc(d){const url=d.drive_file_id?`https://drive.google.com/uc?export=download&id=${encodeURIComponent(d.drive_file_id)}`:(d.file_url||d.url||"");return `<div class="doc"><div><strong>📄 ${esc(d.nama_file||"Surat Pencairan Dana")}</strong><small>Versi final · ${date(d.uploaded_at)}</small></div>${url?`<a class="btn-primary" href="${esc(url)}" download>Download ↓</a>`:'<span>Tautan tidak tersedia</span>'}</div>`;}
function norm(v){return String(v||"").toLowerCase().replace(/[_-]+/g," ").replace(/\s+/g," ").trim();}
function date(v){const d=new Date(v);return Number.isNaN(d.getTime())?"-":d.toLocaleDateString("id-ID",{weekday:"long",day:"numeric",month:"long",year:"numeric"});}
function esc(v){return String(v??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]));}
